Support for "h" and "m" in TimeFormatter
librosa/librosa pull request #1485
Opened 2022-05-21 21:40 UTC by lostanlen

#### Reference Issue
Fixes 1364

#### What does this implement/fix? Explain your changes.
This PR allows to pass `x_axis=` (or `y_axis=`) `"h"` (resp. `"m"`) to `specshow` (or `waveshow`, or anything using `TimeFormatter`) to display time units in hours (resp. minutes) instead of seconds.

#### Any other comments?
* I have updated images `test_time_unit.png` and `test_time_unit_lag.png` to reflect this new feature.

Before:
![baseline](https://user-images.githubusercontent.com/3943142/169669830-d7da2b57-401d-4360-ab65-0b399ceecf98.png)

After:
![result](https://user-images.githubusercontent.com/3943142/169669831-92d7006d-9383-4a7e-b3df-d0407c5e6978.png)

* Given `x_axis="s"`, i suggest `Time (seconds)` as an `xlabel` instead of `Time (s)`. I have updated `__decorate_axis` for this. This is because i find the previous label `Time (s)` difficult to read, especially when the text is small. Likewise for other units: `Time (minutes)` instead of `Time (m)`, etc.

2022-05-22 22:58 UTC, bmcfee commented
This generally looks good at a glance, but I'll be on vacation for the next week and unable to give a proper review until I get back.

2022-06-01 13:35 UTC, bmcfee commented
This LGTM.  I'd like to hold off on merging until we get the 0.9.2 release out though.

2022-06-02 08:31 UTC, lostanlen commented
> This LGTM. I'd like to hold off on merging until we get the 0.9.2 release out though.

OK so, proposed plan:

(1) release 0.9.2
(2) merge this #1485
(3) support strftime formats in specshow (`if "%" in x_axis:` branch)
(3bis, optional: release 0.9.3)
(4) bump requirement: matplotlib 3.6
(5) support two new types in x_coords and y_coords: numpy array of datetime64 and timedelta64
(6) timedelta_like(X, sr, hop_length)
(7) release 0.10
(8) write a blog post (https://librosa.org/blog/) entitled `Specshow time, folks!`
(9) profit

2022-07-01 13:33 UTC, bmcfee approved these changes

2022-07-01 17:53 UTC, bmcfee commented
I think this is good to go, but is there anything here that needs to be updated or integrated with the now merged changes in #1501 ?

2022-07-01 21:51 UTC, lostanlen commented
you're right, i should integrate these new units in #1501 code

2022-07-02 00:02 UTC, bmcfee commented
I think this needs to be rebased to main also.

2022-07-05 12:15 UTC, bmcfee commented on librosa/display.py
> +        if self.unit == "h" or (self.unit==None and (vmax - vmin > 3600)):
Equality testing against `None` is frowned upon; should be `self.unit is None`

2022-07-05 12:17 UTC, bmcfee commented on librosa/display.py
> +    elif isinstance(ax_type, str) and ax_type in time_units.keys():
No need for `.keys()` here, can just say `ax_type in time_units`.

I'm also not sure about the type check here.  All the keys are strings anyway, so any ax_type which fails a string type check will also fail the membership test.

The only reason to do a type check here would be to short-circuit fail the membership test, which could be useful if `ax_type` is ever a non-hashable object.  Can that situation arise?

2022-07-05 12:18 UTC, bmcfee requested changes
A few minor pythonic changes requested, but otherwise looks good!

2022-07-07 10:08 UTC, bmcfee approved these changes

2022-07-07 10:09 UTC, merged