Rainbowgram
librosa/librosa pull request #1612
Opened 2022-12-04 04:53 UTC by EmmaZhao0413

#### Reference Issue
Fix: #1604

#### What does this implement/fix? Explain your changes.
"Rainbowgrams" are a way to simultaneously visualize amplitude and (unwrapped) phase (differential). Add the example to the [gallery](https://librosa.org/doc/main/advanced.html).

2022-12-04 13:07 UTC, bmcfee commented
Thanks @EmmaZhao0413 !  I'm not going to run the CI on this since there are no code changes, but I'm curious if you've built the docs locally to test it out?  Just from a quick skim, I think there are some formatting issues that should get resolved before a proper review.

2022-12-06 20:14 UTC, EmmaZhao0413 commented
> We have tested the cells locally, but we didn't figure out how to test if the example page is expected. Could you explain more?

2022-12-06 20:20 UTC, bmcfee commented
> We have tested the cells locally, but we didn't figure out how to test if the example page is expected. Could you explain more?

Testing this requires building the documentation site, following the instructions in `docs/BUILD.md`.  I pulled the branch down and tried this locally, and it mostly looks good but a few things render incorrectly:

![image](https://user-images.githubusercontent.com/1190540/206014255-ecb6fbb8-8e0f-4c57-b3ce-da612f6f2dfe.png)

Please refer to the [sphinx gallery documentation](https://sphinx-gallery.github.io/stable/syntax.html#embed-rst-in-your-example-python-files) for how to format the comments so that it renders properly.

2022-12-06 20:35 UTC, EmmaZhao0413 commented
We have removed the '%' within the document. It now looks good to us. Could you check if it's ready for merge? Thank you!

2022-12-06 20:38 UTC, bmcfee commented
> We have removed the '%' within the document. It now looks good to us. Could you check if it's ready for merge? Thank you!

Thanks!  Please seem the review comments I added a few minutes ago.  Format-wise it looks okay to me.

2022-12-07 09:00 UTC, lostanlen commented
@EmmaZhao0413 also note that the current code is still based on
```
np.diff(np.unwrap(np.angle(phase), axis=1), axis=1, prepend=0)
```

and not on subtraction of `phase_exp`.

2022-12-11 04:32 UTC, wendywang3315 commented
> Hello @EmmaZhao0413. Also note that the current code is still based on
> 
> ```
> np.diff(np.unwrap(np.angle(phase), axis=1), axis=1, prepend=0)
> ```
> 
> and not on subtraction of `phase_exp`.

Thank you for pointing that out! I should definitely double checked the code next time and I just pushed the changes. Hope it looks good now:)

2022-12-11 15:06 UTC, bmcfee requested changes

2022-12-11 15:06 UTC, bmcfee commented on docs/examples/plot_rainbowgram.py
> +`NSynth paper<https://proceedings.mlr.press/v70/engel17a/engel17a.pdf>`
This link is not correctly formatted - please try to build the docs on your own to check these things.

2022-12-11 15:06 UTC, bmcfee commented on docs/examples/plot_rainbowgram.py
> +ax.set_facecolor('#888')
Can you add a colorbar to this one like in the first example?

2022-12-14 11:46 UTC, bmcfee commented on docs/examples/plot_rainbowgram.py
> +fig.colorbar(img, ax=ax)
You have two colorbars here, resulting in 
![image](https://user-images.githubusercontent.com/1190540/207586738-9c1e00d2-df74-48bb-b3c8-8a191010bc1f.png)

2022-12-15 11:29 UTC, bmcfee commented on docs/examples/plot_rainbowgram.py
> +`NSynth paper <https://proceedings.mlr.press/v70/engel17a/engel17a.pdf>`
Format on this is still incorrect; see https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#hyperlinks

2022-12-16 02:10 UTC, bmcfee commented
LGTM, thanks for putting in the effort to clean this up!

2022-12-16 02:10 UTC, merged